name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print text
        run: |
          echo "Hello there Alex!"
      - name: Check working directory
        run: |
          ls -la
